# Generated by Django 5.2.2 on 2025-11-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('activity', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('legal_form', models.CharField(blank=True, max_length=255)),
                ('niu', models.CharField(blank=True, max_length=128)),
                ('validity_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pas encore appelé'), ('in_progress', 'En cours'), ('done', 'Terminé')], default='pending', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_numero', models.CharField(choices=[('invalid', 'Invalide'), ('no_answer', 'Ne décroche pas'), ('voicemail', 'Répondeur'), ('answered', "Décroche l'appel")], max_length=32)),
                ('call_status', models.CharField(blank=True, choices=[('bad_number', 'Mauvais numéro'), ('not_transformer', 'Pas transformateur'), ('callback', 'Rappel'), ('refused', 'Refuse le questionnaire'), ('accepted', 'Accepte le questionnaire')], max_length=32)),
                ('presentation_level', models.CharField(blank=True, choices=[('', 'Vide'), ('partial', 'Partiel'), ('complete', 'Complet')], max_length=16)),
                ('questions_libres_level', models.CharField(blank=True, choices=[('', 'Vide'), ('partial', 'Partiel'), ('complete', 'Complet')], max_length=16)),
                ('questions_orientees_level', models.CharField(blank=True, choices=[('', 'Vide'), ('partial', 'Partiel'), ('complete', 'Complet')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_marked_at', models.DateTimeField(blank=True, null=True)),
                ('recording_started_at', models.DateTimeField(blank=True, null=True)),
                ('recording_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('recording_path', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='home.company')),
            ],
        ),
    ]
