# Generated by Django 5.2.2 on 2025-11-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'Pas encore appelé'), ('in_progress', 'En cours'), ('callback', 'Rappel'), ('done', 'Déjà appelé')], default='pending', max_length=32),
        ),
    ]
