# Generated by Django 5.2.2 on 2025-11-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_callrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='mime_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
